# This is a basic workflow to help you get started with Actions
name: Deployment
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [closed] # when PR closed
    branches: [ dev ] #
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs ssh deploy for CI, CD
    - name: executing remote ssh commands using password
      if: github.event_name == 'pull_request'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }} 
        script: |
          cd DicomProject
          git fetch -all
          git reset --hard origin/dev
          cd client
          yarn install
          yarn start:prod
          cd ../server
          echo ${{ secrets.PASSWORD }}  | sudo -S
          sudo sh run_docker.sh local
          
