global:
  scrape_interval: 10s 
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus' #
    static_configs:
      - targets: ['middleware:8080'] 